/**
 * Oman Oil Marketing Company (OOMCO / نفط عُمان) EV Charging Stations Network
 * Comprehensive database covering all Oman Oil EV stations across ALL of Oman:
 * Muscat, Al Batinah, Al Dakhiliyah, Al Wusta, Dhofar, Al Sharqiyah, Al Dhahirah, 
 * Al Buraimi, Musandam, and Free Zones through 2027.
 * Directly interconnected with VoltOman Calculation Engine and Energy Zones DB.
 */

export interface EnergyZoneLink {
  zoneId: string;
  zoneTitleEn: string;
  zoneTitleAr: string;
  zoneTypeEn: string;
  zoneTypeAr: string;
  cleanEnergySourceEn: string;
  cleanEnergySourceAr: string;
  linkedCompanies: string[];
  keyIncentivesEn: string[];
  keyIncentivesAr: string[];
  totalCleanPowerMw: number;
  evFleetSynergyEn: string;
  evFleetSynergyAr: string;
}

export interface EvChargingStation {
  id: string;
  nameEn: string;
  nameAr: string;
  governorateEn: string;
  governorateAr: string;
  zoneId: 'sohar' | 'duqm' | 'salalah' | 'khazaen' | 'rusayl' | 'nizwa' | 'sur' | 'mazunah' | 'highway';
  zoneNameEn: string;
  zoneNameAr: string;
  operatorId: 'oomco_ev';
  operatorNameEn: string;
  operatorNameAr: string;
  hasElectricalCharge: boolean; // Confirmed electrical car charging available
  isCarServiceStation: boolean; // Full car service station with verified electrical charging
  realAddressEn: string;
  realAddressAr: string;
  powerKw: number;
  portsCount: number;
  availablePortsNow: number;
  connectorTypes: string[];
  lat: number;
  lng: number;
  status: 'OPERATIONAL' | 'UNDER_CONSTRUCTION_2025_2026' | 'PLANNED_2027_PIPELINE';
  yearCommissioned: number; // 2023, 2024, 2025, 2026, 2027
  tariffOmrPerKwh: number;
  tariffTier: 'TIER_1' | 'TIER_2' | 'TIER_3';
  isFreeZoneHub: boolean;
  freeZoneSynergyEn: string;
  freeZoneSynergyAr: string;
  realtimeOccupancyPct: number;
  energyZoneLink?: EnergyZoneLink;
  // Corridors & highway waypoint linkage for VoltOman
  corridorTag?: 'Adam-Thumrait-Salalah' | 'Batinah' | 'Nizwa Road' | 'Sharqiyah' | 'Duqm SEZ' | 'Muscat Metro' | 'Dhahirah-Buraimi' | 'Musandam';
  waypointKm?: number;
}

// ========================================================
// ENERGY ZONES DATABASE - DIRECT LINKAGE
// ========================================================
export const ENERGY_ZONES_DATABASE: Record<string, EnergyZoneLink> = {
  sohar: {
    zoneId: 'sohar',
    zoneTitleEn: 'Sohar Free Zone & Industrial Port',
    zoneTitleAr: 'المنطقة الحرة بصحار والميناء الصناعي',
    zoneTypeEn: 'Global Industrial & Logistics Hub',
    zoneTypeAr: 'مركز صناعي ولوجستي عالمي',
    cleanEnergySourceEn: '50 MW Sohar Solar PV Farm + Heavy Industry Cogeneration + Green Hydrogen Integration',
    cleanEnergySourceAr: 'محطة صحار للطاقة الشمسية بقدرة 50 م.و + توليد مشترك صناعي + مجمع الهيدروجين الأخضر',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Sohar Aluminum', 'Jindal Shadeed Iron & Steel', 'Vale Oman Pelletizing', 'Freezone EV Fleet Depot'],
    keyIncentivesEn: [
      '100% foreign ownership with 0% corporate tax for up to 25 years',
      'Direct land allocation with pre-connected heavy 33kV & 132kV clean power feeds',
      'Exemption from all customs duties on EV machinery and fleet imports',
      'Single-window fast-track permitting via SOHAR Port and Freezone One-Stop Shop'
    ],
    keyIncentivesAr: [
      'ملكية أجنبية 100% مع إعفاء ضريبي على الشركات يصل إلى 25 عاماً',
      'تخصيص أراضٍ مباشر مع شبكات تغذية كهربائية صناعية نظيفة 33 و 132 ك.ف',
      'إعفاء جمركي كامل على استيراد شواحن المركبات الكهربائية ومعدات النقل النظيف',
      'إجراءات محطة واحدة متكاملة لتراخيص تشغيل أساطيل المركبات الكهربائية'
    ],
    totalCleanPowerMw: 50,
    evFleetSynergyEn: 'High-speed heavy vehicle DC charging corridors directly powered by localized solar farms, supporting zero-emission freight corridors linking Sohar to UAE and Muscat.',
    evFleetSynergyAr: 'شواحن فائقة السرعة للشاحنات الثقيلة وسيارات الركاب تعتمد على الطاقة الشمسية، لدعم أساطيل النقل النظيف بين صحار ومسقط ودولة الإمارات.'
  },
  duqm: {
    zoneId: 'duqm',
    zoneTitleEn: 'Special Economic Zone at Duqm (SEZAD)',
    zoneTitleAr: 'المنطقة الاقتصادية الخاصة بالدقم (SEZAD)',
    zoneTypeEn: 'Multimodal Mega Zone & Green Hydrogen Capital',
    zoneTypeAr: 'المنطقة الاقتصادية الكبرى وعاصمة الهيدروجين الأخضر',
    cleanEnergySourceEn: 'Hyport Duqm Green Ammonia & Hydrogen 1.3 GW Solar/Wind Pipeline + Duqm Wind Corridor',
    cleanEnergySourceAr: 'مشروع هاي بورت الدقم بقدرة 1.3 جيجاواط شمس ورياح + ممرات الرياح بالوسطى',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Hyport Duqm', 'Karwa Motors Oman', 'OQ8 Duqm Refinery', 'Port of Duqm Authority'],
    keyIncentivesEn: [
      'Zero corporate tax for 30 years renewable',
      'Zero customs duties on capital goods and raw materials',
      'Access to dedicated heavy industry clean energy feeder corridors',
      'Subsidized industrial utility tariffs for green mobility infrastructure'
    ],
    keyIncentivesAr: [
      'إعفاء ضريبي لمدة 30 عاماً قابل للتجديد لمشاريع النقل النظيف',
      'إعفاء جمركي كامل على مدخلات التصنيع ومعدات محطات الشحن',
      'ممرات طاقة نظيفة مخصصة من محطات الرياح والشمس بالدقم',
      'تعرفة تفضيلية مدعومة لكهرباء البنية الأساسية للمركبات الكهربائية'
    ],
    totalCleanPowerMw: 320,
    evFleetSynergyEn: 'Anchor hub for long-haul desert EV transport connecting Central Oman to maritime shipping lanes.',
    evFleetSynergyAr: 'مركز محوري للشحن فائق السرعة لدعم شاحنات وحافلات كروة الكهربائية وربط المنطقة بميناء الدقم ومحافظة مسقط.'
  },
  salalah: {
    zoneId: 'salalah',
    zoneTitleEn: 'Salalah Free Zone & Deep Sea Port',
    zoneTitleAr: 'المنطقة الحرة بصلالة وميناء صلالة البحري',
    zoneTypeEn: 'Global Transshipment Hub & Petrochemical Complex',
    zoneTypeAr: 'مركز إعادة شحن عالمي ومجمع بتروكيماويات',
    cleanEnergySourceEn: '50 MW Dhofar Wind Farm + Salalah OQ Green Hydrogen/Ammonia Facility',
    cleanEnergySourceAr: 'محطة رياح ظفار بقدرة 50 م.و + مجمع أوكيو للهيدروجين والأمونيا الخضراء بصلالة',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Salalah Port Services', 'OQ Chemicals', 'Octal Petrochemicals', 'Dhofar Integrated Energy'],
    keyIncentivesEn: [
      'Strategic Indian Ocean maritime lane location with 0% corporate tax for 30 years',
      '100% foreign ownership with zero customs duties',
      'Direct intermodal logistics corridor to Salalah International Airport and Free Zone',
      'Priority green power allocation under Oman Net Zero 2050 framework'
    ],
    keyIncentivesAr: [
      'موقع استراتيجي على بحر العرب مع إعفاء ضريبي 30 سنة',
      'ملكية أجنبية 100% مع إعفاء جمركي للمعدات الكهربائية',
      'ربط لوجستي مباشر مع ميناء صلالة والمطار الدولي والمحطة البرية',
      'أولوية التزود بالطاقة النظيفة بموجب الخطة الوطنية للحياد الصفري 2050'
    ],
    totalCleanPowerMw: 90,
    evFleetSynergyEn: 'Southern terminal charging hub for vehicles traversing the 1,020 km national highway corridor from Muscat.',
    evFleetSynergyAr: 'المحطة الجنوبية الكبرى لإنهاء مسار 1,020 كم السريع وتغذية أساطيل التوزيع المحلية بظفار بطاقة الرياح النظيفة.'
  },
  khazaen: {
    zoneId: 'khazaen',
    zoneTitleEn: 'Khazaen Economic City',
    zoneTitleAr: 'مدينة خزائن الاقتصادية (جنوب الباطنة)',
    zoneTypeEn: 'Integrated Inland Logistics & Dry Port Mega Hub',
    zoneTypeAr: 'المدينة اللوجستية المتكاملة والميناء الجاف',
    cleanEnergySourceEn: 'Khazaen Solar Rooftop Distributed Generation + Manah Solar 500MW Interconnection Grid Feed',
    cleanEnergySourceAr: 'محطات الطاقة الشمسية على أسطح المستودعات + الربط مع مشروع منح 500 م.و',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Khazaen Dry Port (Asyad)', 'Muscat Central Fruit & Veg Market', 'Naqel Logistics Fleet'],
    keyIncentivesEn: [
      'Strategic intersection between Batinah Expressway, Muscat Expressway and Sultan Qaboos Highway',
      'Pre-zoned EV commercial fleet parking and fast-charging yards',
      'Streamlined customs clearance directly at the Dry Port terminal',
      'Attractive long-term industrial lease rates with clean utility hookups'
    ],
    keyIncentivesAr: [
      'موقع استراتيجي يربط طريق الباطنة السريع بطريق مسقط السريع',
      'مواقف وساحات شحن تجاري سريع مخصصة للشاحنات والحافلات الكهربائية',
      'تخليص جمركي فوري ومباشر في ميناء خزائن الجاف',
      'أسعار إيجار تشجيعية طويلة المدى مع ربط فوري بالطاقة النظيفة'
    ],
    totalCleanPowerMw: 35,
    evFleetSynergyEn: 'The primary consolidation and staging ground for last-mile and regional electric delivery vans and heavy haulers.',
    evFleetSynergyAr: 'المحطة المركزية لتجميع وشحن مركبات التوصيل الكهربائي والشاحنات الثقيلة بين محافظات الباطنة ومسقط والداخلية.'
  },
  rusayl: {
    zoneId: 'rusayl',
    zoneTitleEn: 'Rusayl Industrial City & Knowledge Oasis Muscat (KOM)',
    zoneTitleAr: 'مدينة الرسيل الصناعية وواحة المعرفة مسقط',
    zoneTypeEn: 'Advanced Manufacturing & Clean Tech Innovation Park',
    zoneTypeAr: 'مركز الصناعات المتقدمة وواحة التكنولوجيا النظيفة',
    cleanEnergySourceEn: 'Madayn Clean Energy Microgrid + Rooftop Solar Net Metering Program',
    cleanEnergySourceAr: 'الشبكة الذكية المصغرة لمدائن + برنامج الطاقة الشمسية الكهروضوئية الموزعة',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Voltamp Energy SAOG', 'National Detergent', 'Amiantit Oman', 'Maysan EV R&D Labs'],
    keyIncentivesEn: [
      'Proximity to Muscat capital city and Sultan Qaboos University research ecosystem',
      'Subsidized industrial utility tariffs for technology R&D facilities',
      'Exemption from personal income tax and custom duties on prototype parts',
      'Direct high-voltage grid substation capacity supporting high-throughput multi-bay chargers'
    ],
    keyIncentivesAr: [
      'قرب مباشر من العاصمة مسقط وبيئة البحوث بجامعة السلطان قابوس',
      'تعرفة صناعية تفضيلية لمراكز بحوث تقنيات وتطوير المركبات الكهربائية',
      'إعفاءات ضريبية وجمركية على قطع ومكونات أجهزة الشحن والبطاريات',
      'محطات تحويل كهربائية عالية القدرة تغذي شواحن متزامنة متعددة المنافذ'
    ],
    totalCleanPowerMw: 25,
    evFleetSynergyEn: 'Urban and industrial dual-purpose charging depot servicing commercial transport and commuter fleets in Muscat.',
    evFleetSynergyAr: 'محطة مزدوجة لخدمة النقل الصناعي بالرسيل وسيارات موظفي واحة المعرفة مسقط.'
  },
  nizwa: {
    zoneId: 'nizwa',
    zoneTitleEn: 'Nizwa Industrial City',
    zoneTitleAr: 'مدينة نزوى الصناعية (الداخلية)',
    zoneTypeEn: 'Interior Logistics & Mountain Route Launchpad',
    zoneTypeAr: 'مركز لوجستي للداخلية وبوابة الطرق الجبلية',
    cleanEnergySourceEn: '500 MW Manah I & II Mega Solar PV Interconnected Transmission Line',
    cleanEnergySourceAr: 'خط الربط المباشر مع محطتي منح 1 ومنح 2 للطاقة الشمسية (1000 م.و)',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Nizwa Mining & Minerals', 'Al Dakhiliyah Transport', 'Madayn Nizwa Services'],
    keyIncentivesEn: [
      'Prime gateway location before commencing desert transit or mountain ascents (Jabal Akhdar/Shams)',
      'Direct off-take from world-class Manah Solar Complex at competitive tariff rates',
      'Available industrial plots equipped with heavy vehicular ingress and egress infrastructure',
      'Full Madayn single-window licensing'
    ],
    keyIncentivesAr: [
      'موقع استراتيجي كبوابة انطلاق قبل مسارات الصحراء وصعود الجبال الشاهقة',
      'تغذية كهربائية مباشرة من مجمع منح العملاق للطاقة الشمسية بتكلفة منافسة',
      'مخططات مجهزة بمسارات دخول وخروج مخصصة للمركبات الثقيلة والشاحنات',
      'تراخيص تشغيل سريعة عبر نافذة مدائن الاستثمارية'
    ],
    totalCleanPowerMw: 40,
    evFleetSynergyEn: 'Strategic staging station where battery packs are topped off before navigating mountain inclines or continuing southward.',
    evFleetSynergyAr: 'محطة استراتيجية حاسمة لشحن البطاريات إلى 80-90% قبل صعود الجبل الأخضر أو بدء طريق هيماء الصحراوي.'
  },
  sur: {
    zoneId: 'sur',
    zoneTitleEn: 'Sur Industrial City & Coastal Hub',
    zoneTitleAr: 'مدينة صور الصناعية والمجمع الساحلي',
    zoneTypeEn: 'Petrochemical, LNG & Maritime Eco-Zone',
    zoneTypeAr: 'مجمع الغاز الطبيعي المسال والبتروكيماويات والخدمات البحرية',
    cleanEnergySourceEn: 'Sur Gas Plant Cogeneration + Planned 100MW Coastal Solar & Waste Heat Recovery',
    cleanEnergySourceAr: 'محطة التوليد المشترك بصور + مشروع الطاقة الشمسية الساحلية واسترداد الحرارة',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Oman LNG LLC', 'OMIFCO Fertilizer', 'Sur Maritime Services'],
    keyIncentivesEn: [
      'Direct coastal access with deep-water terminal facilities',
      'Robust industrial infrastructure for heavy hydrogen and electrical mobility conversion',
      'Exemption from corporate income tax for up to 30 years',
      'Access to dedicated commercial fleet recharging corridors along Sharqiyah expressway'
    ],
    keyIncentivesAr: [
      'واجهة بحرية استراتيجية مع تسهيلات الرسو للملاحة والشحن',
      'بنية صناعية مهيأة لتطبيقات الهيدروجين الأخضر والتنقل الكهربائي',
      'إعفاء ضريبي على الشركات يصل إلى 30 عاماً',
      'ربط مباشر مع طريق الشرقية السريع بشواحن عالية القدرة'
    ],
    totalCleanPowerMw: 30,
    evFleetSynergyEn: 'Recharges coastal heavy industrial fleets and passenger EVs traveling along the Eastern coastline between Muscat and Sur.',
    evFleetSynergyAr: 'تغذية أساطيل النقل الثقيل لقطاع الغاز الطبيعي ومركبات الركاب على مسار طريق الشرقية السريع.'
  },
  mazunah: {
    zoneId: 'mazunah',
    zoneTitleEn: 'Al Mazunah Free Zone',
    zoneTitleAr: 'المنطقة الحرة بالمزيونة (الحدودية)',
    zoneTypeEn: 'Cross-Border Gateway & Free Trade Logistics Hub',
    zoneTypeAr: 'بوابة التجارة الحرة والخدمات اللوجستية عبر الحدود',
    cleanEnergySourceEn: 'Dhofar Hybrid Off-Grid Clean Power System (Solar + Wind + Smart Storage BESS)',
    cleanEnergySourceAr: 'المنظومة الهجينة النظيفة بظفار (طاقة شمسية + رياح + بطاريات تخزين ذكية)',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Mazunah Logistics Terminal', 'Cross-Border Freight Carriers'],
    keyIncentivesEn: [
      'Strategic border location facilitating transit trade between Oman, Yemen, and GCC markets',
      'Exemption from income taxes for 30 years',
      'No customs duties on imported and exported goods',
      'Simplified trade procedures with specialized commercial cargo clearance'
    ],
    keyIncentivesAr: [
      'موقع حدودي استراتيجي ينشط تجارة العبور بين عُمان واليمن ودول الخليج',
      'إعفاء كامل من ضريبة الدخل لمدة 30 عاماً',
      'إعفاء جمركي شامل على البضائع الداخلة والخارجة',
      'تسهيلات تجارية ميسرة وتخليص سريع لحاويات الشحن'
    ],
    totalCleanPowerMw: 15,
    evFleetSynergyEn: 'Frontier cross-border charging station enabling zero-emission heavy commercial freight across the southwestern boundary.',
    evFleetSynergyAr: 'أقصى محطة شحن حدودية بالجنوب الغربي لتأمين تنقل الشاحنات التجارية الخضراء.'
  },
  highway: {
    zoneId: 'highway',
    zoneTitleEn: 'National Desert Highway Corridors (Adam - Haima - Thumrait)',
    zoneTitleAr: 'المحاور الصحراوية السريعة (أدم - هيماء - ثمريت)',
    zoneTypeEn: 'National Desert EV Spine & Logistics Lifeline',
    zoneTypeAr: 'الشريان الصحراوي الوطني للتنقل السريع',
    cleanEnergySourceEn: 'Distributed Highway Solar PV Microgrids + High-Capacity Battery Energy Storage Systems (BESS)',
    cleanEnergySourceAr: 'محطات طاقة شمسية موزعة على الاستراحات + بطاريات تخزين طاقة فائقة السعة',
    linkedCompanies: ['Oman Oil Marketing Company (OOMCO)', 'Oman Logistics Center (ASYAD)', 'National Highway Services'],
    keyIncentivesEn: [
      'Strategically spaced every 120-170 km to prevent desert range anxiety',
      'Heavy-duty liquid-cooled cables resilient up to 55°C ambient temperatures',
      'Subsidized national EV highway tariff tier (Tier 2: 0.088 OMR/kWh)',
      '24/7 solar-backed backup power with zero grid outage vulnerability'
    ],
    keyIncentivesAr: [
      'تباعد مدروس هندسياً كل 120 إلى 170 كم للقضاء التام على قلق نفاد البطارية بالصحراء',
      'كابلات شحن مبردة بالسوائل مصممة لتحمل حرارة الصحراء حتى 55° م',
      'تعرفة مدعومة للمحاور الوطنية (الفئة 2: 0.088 ر.ع / ك.و.س)',
      'طاقة شمسية مدعومة بأنظمة تخزين تضمن استمرارية الخدمة 24/7'
    ],
    totalCleanPowerMw: 60,
    evFleetSynergyEn: 'The critical backbone of Oman’s EV transition, linking Muscat in the north to Salalah in the south across 1,020 km.',
    evFleetSynergyAr: 'العمود الفقري لمنظومة التنقل الكهربائي بسلطنة عُمان، يربط العاصمة مسقط بمدينة صلالة عبر 1,020 كم.'
  }
};

// ========================================================
// ALL OMAN OIL COMPANY (OOMCO EV) CHARGING STATIONS ACROSS OMAN
// Exclusively Oman Oil Company stations covering all governorates and corridors through 2027
// ========================================================
export const EV_CHARGING_STATIONS: EvChargingStation[] = [
  // ----------------------------------------------------
  // MUSCAT GOVERNORATE (Capital Region)
  // ----------------------------------------------------
  {
    id: 'oomco_muscat_qurum_mega',
    nameEn: 'OOMCO EV - Sultan Qaboos Highway Mega Hub (Qurum)',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة القرم الكبرى (شارع السلطان قابوس)',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Muscat Capital Metro',
    zoneNameAr: 'العاصمة مسقط',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sultan Qaboos Street, Qurum Commercial Hub (Opposite Qurum Natural Park), Muscat',
    realAddressAr: 'شارع السلطان قابوس، مجمع القرم التجاري (مقابل حديقة القرم الطبيعية)، مسقط',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO', 'Type 2'],
    lat: 23.6145,
    lng: 58.4890,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Flagship Muscat ultra-fast charging station on Sultan Qaboos Highway with express retail and lounge.',
    freeZoneSynergyAr: 'محطة الشحن السريع الرئيسية لشركة نفط عُمان بشارع السلطان قابوس مع استراحة متكاملة وخدمات تسوق.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Muscat Metro',
    waypointKm: 0
  },
  {
    id: 'oomco_muscat_the_wave_mouj',
    nameEn: 'OOMCO EV - Al Mouj Muscat Waterfront Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة الموج مسقط الساحلية',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Al Mouj Muscat',
    zoneNameAr: 'الموج مسقط',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: '18th November Street, Entrance to Al Mouj Muscat (The Wave Waterfront), Seeb, Muscat',
    realAddressAr: 'شارع 18 نوفمبر، المدخل الرئيسي لمشروع الموج مسقط (الواجهة البحرية)، السيب، مسقط',
    powerKw: 180,
    portsCount: 8,
    availablePortsNow: 6,
    connectorTypes: ['CCS2', 'CHAdeMO', 'Type 2'],
    lat: 23.6288,
    lng: 58.2612,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Premium high-density dual-charger hub situated at the entrance of Al Mouj waterfront development.',
    freeZoneSynergyAr: 'محطة شحن متطورة فائقة السرعة تخدم زوار وقاطني مشروع الموج الساحلي والواجهة البحرية.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Muscat Metro',
    waypointKm: 12
  },
  {
    id: 'oomco_muscat_airport_express',
    nameEn: 'OOMCO EV - Muscat International Airport Express Terminal',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مطار مسقط الدولي السريعة',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Muscat Airport District',
    zoneNameAr: 'منطقة مطار مسقط',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Southern Airport Highway / Muscat International Airport Express Service Area, Seeb',
    realAddressAr: 'طريق المطار الجنوبي السريع / منطقة خدمات مطار مسقط الدولي، ولاية السيب',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 5,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.5933,
    lng: 58.2844,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Airport transit charging hub supporting electric limousines, airline shuttles, and intercity travellers.',
    freeZoneSynergyAr: 'محطة سريعة لخدمة سيارات الأجرة الكهربائية ومركبات المسافرين بين المطار ومختلف المحافظات.',
    realtimeOccupancyPct: 17,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Muscat Metro',
    waypointKm: 8
  },
  {
    id: 'oomco_muscat_msq_madinat',
    nameEn: 'OOMCO EV - Madinat Al Sultan Qaboos Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مدينة السلطان قابوس',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Muscat Commercial',
    zoneNameAr: 'مسقط التجارية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Al Inshirah Street, Madinat Al Sultan Qaboos Commercial District, Bowshar, Muscat',
    realAddressAr: 'شارع الانشراح، المنطقة التجارية بمدينة السلطان قابوس، ولاية بوشر، مسقط',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 23.5980,
    lng: 58.4410,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Urban fast charger located in the central commercial district of MSQ.',
    freeZoneSynergyAr: 'محطة شحن حضرية سريعة بقلب مدينة السلطان قابوس للمركبات اليومية والتنقل السريع.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Muscat Metro',
    waypointKm: 5
  },
  {
    id: 'oomco_muscat_squ_khoudh',
    nameEn: 'OOMCO EV - Al Khoudh & Sultan Qaboos University (SQU) Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة الخوض وجامعة السلطان قابوس (SQU)',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'SQU & Knowledge Corridor',
    zoneNameAr: 'جامعة السلطان قابوس وممر المعرفة',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Mazoon Street, Al Khoudh 6 (Adjacent to Sultan Qaboos University Main Campus), Seeb, Muscat',
    realAddressAr: 'شارع مزون، الخوض السادسة (بجوار الحرم الرئيسي لجامعة السلطان قابوس)، ولاية السيب، مسقط',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 23.5910,
    lng: 58.1720,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Flagship academic and commuter hub directly serving Sultan Qaboos University students, faculty, and Al Khoudh residents.',
    freeZoneSynergyAr: 'محطة رئيسية متطورة تخدم طلاب وأكاديميي جامعة السلطان قابوس والمجتمع السكني بالخوض والسيب بشواحن فائقة السرعة.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Muscat Metro',
    waypointKm: 6
  },
  {
    id: 'oomco_muscat_halban_expressway',
    nameEn: 'OOMCO EV - Muscat Expressway Mega Service Station (Halban)',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة حلبان طريق مسقط السريع الكبرى',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Muscat Expressway Corridor',
    zoneNameAr: 'محور مسقط السريع',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Muscat Expressway (Exit 24), Halban Integrated Service & Fuel Plaza, Muscat',
    realAddressAr: 'طريق مسقط السريع (مخرج 24)، استراحة ومحطة وقود حلبان المتكاملة، محافظة مسقط',
    powerKw: 180,
    portsCount: 8,
    availablePortsNow: 5,
    connectorTypes: ['CCS2', 'CHAdeMO', 'Type 2'],
    lat: 23.6180,
    lng: 58.0450,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'High-capacity expressway transit service hub with premium rest lounge and ultra-fast dual CCS2 dispensers.',
    freeZoneSynergyAr: 'محطة استراحة كبرى فائقة السرعة تخدم حركة المرور العابرة على طريق مسقط السريع مع خدمات تسوق متكاملة.',
    realtimeOccupancyPct: 37,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Batinah',
    waypointKm: 25
  },
  {
    id: 'oomco_muscat_maabilah_expressway',
    nameEn: 'OOMCO EV - Al Maabilah Expressway Service Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة المعبيلة طريق مسقط السريع',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Muscat West Expressway',
    zoneNameAr: 'غرب مسقط السريع',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Muscat Expressway (Exit 27), Al Maabilah South Service Station, Seeb, Muscat',
    realAddressAr: 'طريق مسقط السريع (مخرج 27)، محطة خدمة المعبيلة الجنوبية، ولاية السيب، مسقط',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.6520,
    lng: 58.1150,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Strategic western gateway station feeding high-speed traffic transitioning from Muscat Expressway into Batinah corridor.',
    freeZoneSynergyAr: 'بوابة غرب مسقط الاستراتيجية لخدمة حركة المرور السريعة باتجاه طريق الباطنة السريع.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Batinah',
    waypointKm: 30
  },
  {
    id: 'oomco_muscat_rusayl_industrial',
    nameEn: 'OOMCO EV - Rusayl Industrial City Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مدينة الرسيل الصناعية',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Rusayl Industrial City',
    zoneNameAr: 'مدينة الرسيل الصناعية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Madayn Rusayl Industrial City Main Boulevard (Near Factory Zone), Muscat',
    realAddressAr: 'الشارع الرئيسي لمدينة الرسيل الصناعية (مدائن)، محافظة مسقط',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.5420,
    lng: 58.1810,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.080,
    tariffTier: 'TIER_1',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Dedicated commercial fleet charging hub inside Rusayl Industrial City, directly tied to Madayn solar installations.',
    freeZoneSynergyAr: 'محطة أساطيل صناعية متخصصة بقلب مدينة الرسيل مرتبطة بأنظمة الطاقة الشمسية لمدائن.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Nizwa Road',
    waypointKm: 25
  },
  {
    id: 'oomco_muscat_kom_tech_oasis',
    nameEn: 'OOMCO EV - Knowledge Oasis Muscat (KOM) Tech Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة واحة المعرفة مسقط (KOM)',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Knowledge Oasis Muscat',
    zoneNameAr: 'واحة المعرفة مسقط',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Knowledge Oasis Muscat (KOM 4), Innovation Avenue, Rusayl, Muscat',
    realAddressAr: 'واحة المعرفة مسقط (مبنى كوم 4)، شارع الابتكار، الرسيل، مسقط',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 23.5510,
    lng: 58.1720,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.075,
    tariffTier: 'TIER_1',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Tech campus hub catering to IT companies, startups, and university researchers.',
    freeZoneSynergyAr: 'محطة تكنولوجية حديثة لخدمة شركات التقنية ورواد الأعمال والباحثين بواحة المعرفة.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Muscat Metro',
    waypointKm: 28
  },
  {
    id: 'oomco_muscat_amerat_mountain',
    nameEn: 'OOMCO EV - Al Amerat Mountain Gateway Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة العامرات وبوابة طريق الجبل',
    governorateEn: 'Muscat',
    governorateAr: 'مسقط',
    zoneId: 'rusayl',
    zoneNameEn: 'Al Amerat - Sharqiyah Gateway',
    zoneNameAr: 'العامرات - مدخل الشرقية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Amerat - Bowshar Mountain Pass Highway, Al Amerat Heights, Muscat',
    realAddressAr: 'شارع عقبة العامرات - بوشر الجبلي، مرتفعات العامرات، محافظة مسقط',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.5010,
    lng: 58.5020,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.080,
    tariffTier: 'TIER_1',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Positioned at the base of the steep Amerat-Bousher mountain pass, enabling pre-climb battery top-up.',
    freeZoneSynergyAr: 'محطة واقعة عند أسفل عقبة العامرات-بوشر لشحن المركبات قبل الصعود الجبلي.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.rusayl,
    corridorTag: 'Sharqiyah',
    waypointKm: 18
  },

  // ----------------------------------------------------
  // NORTH & SOUTH AL BATINAH GOVERNORATES
  // ----------------------------------------------------
  {
    id: 'oomco_batinah_barka_expressway',
    nameEn: 'OOMCO EV - Barka South Expressway Mega Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة بركاء طريق الباطنة السريع',
    governorateEn: 'South Al Batinah',
    governorateAr: 'جنوب الباطنة',
    zoneId: 'khazaen',
    zoneNameEn: 'Barka Expressway Corridor',
    zoneNameAr: 'طريق بركاء السريع',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Al Batinah Expressway, Barka South Integrated Service Area (Km 45)',
    realAddressAr: 'طريق الباطنة السريع، محطة استراحة بركاء جنوب المتكاملة (كيلومتر 45)',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 5,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.6650,
    lng: 57.8920,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'High-throughput expressway mega-station serving heavy commuter traffic between Muscat and Batinah.',
    freeZoneSynergyAr: 'محطة استراحة كبرى على طريق الباطنة السريع مجهزة بشواحن فائقة السرعة للمسافرين.',
    realtimeOccupancyPct: 17,
    energyZoneLink: ENERGY_ZONES_DATABASE.khazaen,
    corridorTag: 'Batinah',
    waypointKm: 55
  },
  {
    id: 'oomco_khazaen_dryport_station',
    nameEn: 'OOMCO EV - Khazaen Economic City Dry Port Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ميناء خزائن الجاف بمدينة خزائن',
    governorateEn: 'South Al Batinah',
    governorateAr: 'جنوب الباطنة',
    zoneId: 'khazaen',
    zoneNameEn: 'Khazaen Economic City',
    zoneNameAr: 'مدينة خزائن الاقتصادية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Khazaen Economic City Central Logistics Spine (Next to Dry Port Gate), Barka',
    realAddressAr: 'مدينة خزائن الاقتصادية، المحور اللوجستي المركزي (بجوار بوابة الميناء الجاف)، بركاء',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.6420,
    lng: 57.8650,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.085,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Dedicated logistics EV depot adjacent to Khazaen Dry Port container terminal.',
    freeZoneSynergyAr: 'محطة أساطيل شحن كهربائي ملاصقة للميناء الجاف بمدينة خزائن الاقتصادية.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.khazaen,
    corridorTag: 'Batinah',
    waypointKm: 65
  },
  {
    id: 'oomco_khazaen_megahub_pipeline',
    nameEn: 'OOMCO EV - Khazaen Central Megawatt Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة الميجاواط المركزية بمدينة خزائن',
    governorateEn: 'South Al Batinah',
    governorateAr: 'جنوب الباطنة',
    zoneId: 'khazaen',
    zoneNameEn: 'Khazaen Economic City',
    zoneNameAr: 'مدينة خزائن الاقتصادية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Khazaen Economic City Megawatt Charging Plaza, South Barka Corridor',
    realAddressAr: 'ساحة شحن الميجاواط المركزية بمدينة خزائن الاقتصادية، جنوب بركاء',
    powerKw: 240,
    portsCount: 8,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'MCS Mega'],
    lat: 23.6550,
    lng: 57.8820,
    status: 'PLANNED_2027_PIPELINE',
    yearCommissioned: 2027,
    tariffOmrPerKwh: 0.080,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Strategic megawatt heavy commercial charging depot directly supplied by local rooftop solar microgrids.',
    freeZoneSynergyAr: 'محطة ميجاواط استراتيجية للشاحنات الكهربائية الكبرى مدعومة بمزارع شمسية موضعية.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.khazaen,
    corridorTag: 'Batinah',
    waypointKm: 68
  },
  {
    id: 'oomco_batinah_suwaiq_expressway',
    nameEn: 'OOMCO EV - Al Suwaiq Expressway Service Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة السويق طريق الباطنة السريع',
    governorateEn: 'North Al Batinah',
    governorateAr: 'شمال الباطنة',
    zoneId: 'sohar',
    zoneNameEn: 'Al Suwaiq Corridor',
    zoneNameAr: 'محور السويق السريع',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Al Batinah Expressway, Al Suwaiq Highway Rest & Fuel Plaza (Km 120)',
    realAddressAr: 'طريق الباطنة السريع، استراحة ومحطة وقود السويق الكبرى (كيلومتر 120)',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.8420,
    lng: 57.4350,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Mid-point transit charging rest stop between Barka and Sohar along the Batinah Expressway.',
    freeZoneSynergyAr: 'محطة استراحة وشحن سريعة بمنتصف المسافة بين بركاء وصحار على طريق الباطنة السريع.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Batinah',
    waypointKm: 115
  },
  {
    id: 'oomco_batinah_saham_coastal',
    nameEn: 'OOMCO EV - Saham Coastal Fast Waypoint',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة صحم الساحلية السريعة',
    governorateEn: 'North Al Batinah',
    governorateAr: 'شمال الباطنة',
    zoneId: 'sohar',
    zoneNameEn: 'Saham - Sohar Corridor',
    zoneNameAr: 'محور صحم - صحار',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sultan Qaboos Highway (Route 1), Saham Town Center Junction',
    realAddressAr: 'طريق السلطان قابوس الساحلي (طريق 1)، تقاطع مركز ولاية صحم',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 24.1800,
    lng: 56.8850,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Connecting urban coastal commuters with high-speed DC charging prior to entering Sohar industrial zone.',
    freeZoneSynergyAr: 'خدمة حركة المرور الساحلية وسكان صحم قبل الدخول إلى المنطقة الصناعية بصحار.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Batinah',
    waypointKm: 165
  },
  {
    id: 'oomco_sohar_freezone_green_hub',
    nameEn: 'OOMCO EV - Sohar Freezone Green Mobility Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة المنطقة الحرة بصحار للتنقل الأخضر',
    governorateEn: 'North Al Batinah',
    governorateAr: 'شمال الباطنة',
    zoneId: 'sohar',
    zoneNameEn: 'Sohar Freezone',
    zoneNameAr: 'المنطقة الحرة بصحار',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sohar Free Zone Gate 1 / Liwa Highway Interchange, Sohar Port Corridor',
    realAddressAr: 'المنطقة الحرة بصحار، البوابة رقم 1 / تقاطع طريق لوى السريع، مجمع صحار',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 24.4750,
    lng: 56.6280,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'State-of-the-art charging hub inside Sohar Freezone, powered by dedicated 50 MW Sohar Solar clean energy grid.',
    freeZoneSynergyAr: 'محطة نموذجية متكاملة للتنقل الأخضر داخل حرة صحار تعتمد على شبكة الطاقة النظيفة لمزرعة صحار الشمسية.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Batinah',
    waypointKm: 215
  },
  {
    id: 'oomco_sohar_port_terminal',
    nameEn: 'OOMCO EV - Sohar Port Deep-Sea Container Terminal Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ميناء صحار لمحطة الحاويات',
    governorateEn: 'North Al Batinah',
    governorateAr: 'شمال الباطنة',
    zoneId: 'sohar',
    zoneNameEn: 'Sohar Port',
    zoneNameAr: 'ميناء صحار',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Port of Sohar Deep-Water Marine Terminal Access Road, Sohar Industrial Area',
    realAddressAr: 'طريق الدخول الرئيسي لميناء صحار الصناعي ومحطة الحاويات، صحار',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'MCS Mega'],
    lat: 24.4980,
    lng: 56.6450,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Marine container terminal EV hub serving port haulers, pilot vehicles, and customs transport.',
    freeZoneSynergyAr: 'محطة أساطيل الميناء البحري لشحن شاحنات الحاويات ومركبات التخليص الجمركي.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Batinah',
    waypointKm: 220
  },
  {
    id: 'oomco_batinah_shinas_border',
    nameEn: 'OOMCO EV - Shinas Northern Border Transit Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة شناص الحدودية الشمالية',
    governorateEn: 'North Al Batinah',
    governorateAr: 'شمال الباطنة',
    zoneId: 'sohar',
    zoneNameEn: 'Shinas Border Gateway',
    zoneNameAr: 'بوابة شناص الحدودية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 1, Shinas Border Transit Plaza (Near Khatmat Malaha Border Crossing)',
    realAddressAr: 'طريق 1، محطة عبور شناص الحدودية (بالقرب من منفذ خطمة ملاحة الحدودي)',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 24.7450,
    lng: 56.4650,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Final fast-charge outpost before crossing the northern border into the United Arab Emirates.',
    freeZoneSynergyAr: 'آخر محطة شحن سريعة لشركة نفط عُمان قبل منفذ خطمة الملاحة باتجاه دولة الإمارات.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Batinah',
    waypointKm: 265
  },

  // ----------------------------------------------------
  // AL DAKHILIYAH GOVERNORATE
  // ----------------------------------------------------
  {
    id: 'oomco_dakhiliyah_bidbid_valley',
    nameEn: 'OOMCO EV - Bidbid Valley Highway Service Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة وادي بدبد السريعة',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Bidbid Pass',
    zoneNameAr: 'ممر بدبد',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 15 (Muscat - Interior Dual Carriageway), Fanja / Bidbid Valley Station',
    realAddressAr: 'طريق 15 (شارع مسقط - نزوى المزدوج)، محطة فنجاء / وادي بدبد',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.4150,
    lng: 58.1250,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Crucial gateway linking the capital to the interior valleys, positioned where Muscat highway meets the mountain ascent.',
    freeZoneSynergyAr: 'محطة مدخل محافظة الداخلية بوادي بدبد لدعم المركبات قبل صعود التضاريس الجبلية.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 50
  },
  {
    id: 'oomco_dakhiliyah_samail_industrial',
    nameEn: 'OOMCO EV - Samail Industrial City Depot',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مدينة سمائل الصناعية',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Samail Industrial City',
    zoneNameAr: 'مدينة سمائل الصناعية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Madayn Samail Industrial City Main Entrance, Al Dakhiliyah',
    realAddressAr: 'المدخل الرئيسي لمدينة سمائل الصناعية (مدائن)، محافظة الداخلية',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.3100,
    lng: 57.9850,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Supplying fast DC power for regional light manufacturing and transport fleets in Samail.',
    freeZoneSynergyAr: 'توفير الشحن السريع للمركبات الخفيفة والشاحنات بمدينة سمائل الصناعية.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 85
  },
  {
    id: 'oomco_dakhiliyah_birkat_mouz',
    nameEn: 'OOMCO EV - Birkat Al Mouz Foothills Ascent Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة بركة الموز لصعود الجبل الأخضر',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Birkat Al Mouz Gateway',
    zoneNameAr: 'بوابة بركة الموز',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 21 / Jabal Akhdar Mountain Ascent Highway Junction, Birkat Al Mouz',
    realAddressAr: 'تقاطع طريق 21 مع طريق صعود الجبل الأخضر، بركة الموز',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.9250,
    lng: 57.6750,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Last high-speed recharge depot before ascending the steep 2,000m climb up Jabal Akhdar.',
    freeZoneSynergyAr: 'محطة الشحن الحيوية عند سفح الجبل الأخضر لملء البطارية قبل الصعود الجبلي الحاد (+1800 م).',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 130
  },
  {
    id: 'oomco_dakhiliyah_nizwa_grand',
    nameEn: 'OOMCO EV - Nizwa Grand Oasis Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة نزوى الكبرى (طريق مسقط-نزوى)',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Nizwa City',
    zoneNameAr: 'مدينة نزوى',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 15, Firq Commercial District (Adjacent to Nizwa Grand Mall), Nizwa',
    realAddressAr: 'طريق 15، منطقة فرق التجارية (بجوار نزوى جراند مول)، ولاية نزوى',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.9280,
    lng: 57.5450,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Premier hub in the interior capital, interconnected with the 500MW Manah solar mega-project.',
    freeZoneSynergyAr: 'المحطة الكبرى في عاصمة الداخلية نزوى، متصلة بشبكة مجمع منح للطاقة الشمسية النظيفة.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 155
  },
  {
    id: 'oomco_dakhiliyah_nizwa_industrial',
    nameEn: 'OOMCO EV - Nizwa Industrial City Fast Depot',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مدينة نزوى الصناعية (مدائن)',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Nizwa Industrial City',
    zoneNameAr: 'مدينة نزوى الصناعية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Madayn Nizwa Industrial City Depot, Karsha District, Nizwa',
    realAddressAr: 'مدينة نزوى الصناعية (مدائن)، منطقة كرشاء، ولاية نزوى',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.9450,
    lng: 57.5180,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'High-power commercial depot for mining, quarry, and freight transport within Madayn Nizwa.',
    freeZoneSynergyAr: 'محطة أساطيل صناعية متخصصة لقطاع التعدين والشحن التجاري بمدينة نزوى الصناعية.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 160
  },
  {
    id: 'oomco_dakhiliyah_bahla_oasis',
    nameEn: 'OOMCO EV - Bahla Heritage Oasis Fast Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة بهلاء واحة التراث السريعة',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Bahla District',
    zoneNameAr: 'ولاية بهلاء',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 21, Bahla Historic Oasis Highway Plaza, Al Dakhiliyah',
    realAddressAr: 'طريق 21، محطة واحة بهلاء التاريخية، محافظة الداخلية',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 22.9650,
    lng: 57.2950,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Expanding tourism and intercity EV network along the historic Bahla oasis corridor.',
    freeZoneSynergyAr: 'توسعة شبكة الشحن السياحية والتجارية على مسار واحة بهلاء التاريخية.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 190
  },
  {
    id: 'oomco_dakhiliyah_jabal_akhdar_saiq',
    nameEn: 'OOMCO EV - Jabal Akhdar Saiq Ascent Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة سيق بالجبل الأخضر (القمة)',
    governorateEn: 'Al Dakhiliyah',
    governorateAr: 'الداخلية',
    zoneId: 'nizwa',
    zoneNameEn: 'Jabal Akhdar Summit',
    zoneNameAr: 'قمة الجبل الأخضر',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Saiq Plateau Center Road, Jabal Akhdar High Altitude Station (2,000m Elevation)',
    realAddressAr: 'طريق مركز هضبة سيق، محطة الجبل الأخضر المرتفعة (ارتفاع 2000 متر)',
    powerKw: 100,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 23.0720,
    lng: 57.6650,
    status: 'PLANNED_2027_PIPELINE',
    yearCommissioned: 2027,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Summit mountain charger engineered for cool-climate operation (2,050m elevation) with regenerative descent counseling.',
    freeZoneSynergyAr: 'محطة قمة الجبل الأخضر على ارتفاع 2,050 م لدعم السياحة وتوعية السائقين باسترداد طاقة النزول.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.nizwa,
    corridorTag: 'Nizwa Road',
    waypointKm: 165
  },

  // ----------------------------------------------------
  // AL WUSTA GOVERNORATE & NATIONAL DESERT HIGHWAY (Adam - Salalah)
  // ----------------------------------------------------
  {
    id: 'oomco_wusta_adam_gateway',
    nameEn: 'OOMCO EV - Adam Desert Gateway Service Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة واحة أدم بوابة الصحراء',
    governorateEn: 'Al Dakhiliyah / Al Wusta Gateway',
    governorateAr: 'مدخل أدم / الوسطى',
    zoneId: 'highway',
    zoneNameEn: 'Adam-Thumrait Desert Highway',
    zoneNameAr: 'طريق أدم-ثمريت الصحراوي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Highway 31 (Km 0 of Muscat-Salalah Desert Highway), Adam South Service Plaza',
    realAddressAr: 'طريق 31 (بداية طريق مسقط-صلالة الصحراوي السريع)، استراحة أدم جنوب',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.3780,
    lng: 57.5250,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'The critical northern staging ground before entering the 800 km desert highway stretch toward Dhofar.',
    freeZoneSynergyAr: 'المحطة الشمالية الحاسمة للتزود بالطاقة قبل الدخول في المسار الصحراوي الممتد نحو ظفار.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 225
  },
  {
    id: 'oomco_wusta_ghaba_oasis',
    nameEn: 'OOMCO EV - Ghaba Oasis Desert Rest Stop',
    nameAr: 'نفط عُمان (OOMCO EV) - استراحة غابة الصحراوية الكبرى',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'highway',
    zoneNameEn: 'Adam-Thumrait Desert Highway',
    zoneNameAr: 'طريق أدم-ثمريت الصحراوي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Highway 31 (Km 215), Ghaba Desert Oasis Rest Area & Fuel Stop',
    realAddressAr: 'طريق 31 (كيلومتر 215)، استراحة ومحطة وقود غابة الصحراوية، محافظة الوسطى',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 21.3650,
    lng: 57.3450,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'High-temperature desert waypoint with dedicated solar canopy and active liquid-cooled charging cables.',
    freeZoneSynergyAr: 'محطة صحراوية مجهزة بمظلات شمسية وكابلات مبردة بالسوائل مصممة لتحمل حرارة الصيف الشديدة.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 360
  },
  {
    id: 'oomco_wusta_haima_central',
    nameEn: 'OOMCO EV - Haima Central Desert Supercharger',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة هيماء المركزية السريعة (عاصمة الوسطى)',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'highway',
    zoneNameEn: 'Adam-Thumrait Desert Highway',
    zoneNameAr: 'طريق أدم-ثمريت الصحراوي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Highway 31 (Km 500 Midpoint), Central Haima Capital Rest Area & Supercharger Hub',
    realAddressAr: 'طريق 31 (كيلومتر 500 - نقطة المنتصف)، استراحة ومحطة هيماء المركزية الكبرى، الوسطى',
    powerKw: 180,
    portsCount: 8,
    availablePortsNow: 5,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 19.9580,
    lng: 56.2750,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'The primary mid-route supercharging station at km 535 of the Muscat-Salalah highway, featuring full motel, restaurant, and EV lounge.',
    freeZoneSynergyAr: 'المحطة المركزية الكبرى عند الكيلومتر 535 بمنتصف طريق مسقط-صلالة، مع خدمات فندقية واستراحة متطورة.',
    realtimeOccupancyPct: 38,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 535
  },
  {
    id: 'oomco_wusta_ghaftain_transport',
    nameEn: 'OOMCO EV - Al Ghaftain Transport Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة الغافتين لخدمات الطرق والشاحنات',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'highway',
    zoneNameEn: 'Adam-Thumrait Desert Highway',
    zoneNameAr: 'طريق أدم-ثمريت الصحراوي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Highway 31 (Km 660), Al Ghaftain Highway Rest Area & Truck Transit Stop',
    realAddressAr: 'طريق 31 (كيلومتر 660)، استراحة ومحطة الغافتين لخدمة المسافرين والشاحنات',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 19.1650,
    lng: 55.5180,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Dedicated desert stop ensuring continuous range safety across the vast central desert plain.',
    freeZoneSynergyAr: 'محطة دعم حيوية لضمان الأمان وراحة السائقين عبر سهول صحراء الوسطى الشاسعة.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 670
  },
  {
    id: 'oomco_wusta_qatbit_waypoint',
    nameEn: 'OOMCO EV - Qatbit Desert Waypoint Station',
    nameAr: 'نفط عُمان (OOMCO EV) - استراحة قتبيت الصحراوية',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'highway',
    zoneNameEn: 'Adam-Thumrait Desert Highway',
    zoneNameAr: 'طريق أدم-ثمريت الصحراوي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Highway 31 (Km 780), Qatbit Desert Waypoint & Overnight Rest Stop',
    realAddressAr: 'طريق 31 (كيلومتر 780)، استراحة قتبيت الصحراوية ومحطة شحن المسافرين',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 18.2580,
    lng: 54.4920,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Strategic transit stop preventing range depletion before entering Dhofar governorate borders.',
    freeZoneSynergyAr: 'نقطة توقف ذكية لتأمين مدى البطارية قبل عبور الحدود الإدارية لمحافظة ظفار.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 775
  },
  {
    id: 'oomco_duqm_renaissance_village',
    nameEn: 'OOMCO EV - Duqm Renaissance Village & SEZAD Corridor Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة قرية النهضة بالمنطقة الاقتصادية بالدقم',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'duqm',
    zoneNameEn: 'SEZAD Duqm',
    zoneNameAr: 'المنطقة الاقتصادية بالدقم',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sultan Said bin Taimur Boulevard, SEZAD Renaissance Village District, Duqm',
    realAddressAr: 'شارع السلطان سعيد بن تيمور، مجمع قرية النهضة بالمنطقة الاقتصادية بالدقم',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 19.6450,
    lng: 57.7020,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Commercial service station in SEZAD Duqm catering to workforce logistics and Karwa electric buses.',
    freeZoneSynergyAr: 'محطة تجارية متطورة لخدمة أساطيل النقل وحافلات كروة الكهربائية بالمنطقة الاقتصادية بالدقم.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.duqm,
    corridorTag: 'Duqm SEZ',
    waypointKm: 520
  },
  {
    id: 'oomco_duqm_port_marine',
    nameEn: 'OOMCO EV - Duqm Port Marine Terminal Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ميناء الدقم البحري',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'duqm',
    zoneNameEn: 'Port of Duqm',
    zoneNameAr: 'ميناء الدقم',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Port of Duqm Commercial Quay & Marine Logistics Highway, Duqm',
    realAddressAr: 'طريق الرصيف التجاري واللوجستي لميناء الدقم، محافظة الوسطى',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 19.6720,
    lng: 57.7280,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Directly servicing Port of Duqm logistics, bunkering vehicles, and maritime terminal staff.',
    freeZoneSynergyAr: 'شواحن فائقة السرعة لخدمة ساحات ميناء الدقم ومركبات التموين والشحن البحري.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.duqm,
    corridorTag: 'Duqm SEZ',
    waypointKm: 535
  },
  {
    id: 'oomco_duqm_heavy_industrial',
    nameEn: 'OOMCO EV - Duqm Heavy Industrial Megawatt Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة الميجاواط بالمنطقة الصناعية الثقيلة بالدقم',
    governorateEn: 'Al Wusta',
    governorateAr: 'الوسطى',
    zoneId: 'duqm',
    zoneNameEn: 'Duqm Heavy Industrial Zone',
    zoneNameAr: 'المنطقة الصناعية الثقيلة بالدقم',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'SEZAD Heavy Industrial Zone Megawatt Corridor (Near OQ8 Refinery Gate), Duqm',
    realAddressAr: 'المنطقة الصناعية الثقيلة بالدقم (بالقرب من بوابة مصفاة OQ8)، الدقم',
    powerKw: 240,
    portsCount: 8,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'MCS Mega'],
    lat: 19.6100,
    lng: 57.6580,
    status: 'PLANNED_2027_PIPELINE',
    yearCommissioned: 2027,
    tariffOmrPerKwh: 0.082,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'High-power depot tied to Hyport Duqm green ammonia and wind power generation.',
    freeZoneSynergyAr: 'محطة ميجاواط مخصصة للشاحنات الثقيلة ترتبط بمشاريع طاقة الرياح والهيدروجين الأخضر بالدقم.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.duqm,
    corridorTag: 'Duqm SEZ',
    waypointKm: 550
  },

  // ----------------------------------------------------
  // DHOFAR GOVERNORATE (Southern Hub)
  // ----------------------------------------------------
  {
    id: 'oomco_dhofar_thumrait_ascent',
    nameEn: 'OOMCO EV - Thumrait Mountain Ascent Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ثمريت لصعود جبال ظفار',
    governorateEn: 'Dhofar',
    governorateAr: 'ظفار',
    zoneId: 'highway',
    zoneNameEn: 'Thumrait Highway Hub',
    zoneNameAr: 'محور ثمريت السريع',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Highway 31 (Km 920), Thumrait North Gateway (Pre-Salalah Mountain Descent)',
    realAddressAr: 'طريق 31 (كيلومتر 920)، بوابة ثمريت الشمالية (قبل عقبة جبال ظفار)، ثمريت',
    powerKw: 150,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 17.6320,
    lng: 54.0320,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'The southern inland gateway ensuring sufficient SOC before navigating the coastal mountain descent into Salalah.',
    freeZoneSynergyAr: 'البوابة الجنوبية لشحن البطاريات قبل خوض الانحدار الجبلي الساحلي باتجاه صلالة.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 935
  },
  {
    id: 'oomco_dhofar_salalah_freezone',
    nameEn: 'OOMCO EV - Salalah Freezone Gateway Green Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة المنطقة الحرة بصلالة للتنقل الأخضر',
    governorateEn: 'Dhofar',
    governorateAr: 'ظفار',
    zoneId: 'salalah',
    zoneNameEn: 'Salalah Freezone',
    zoneNameAr: 'المنطقة الحرة بصلالة',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Raysut Industrial Corridor / Salalah Free Zone Gate 2, Salalah',
    realAddressAr: 'شارع ريسوت الصناعي / بوابة المنطقة الحرة بصلالة رقم 2، صلالة',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 16.9450,
    lng: 53.9920,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Flagship clean energy charging terminal inside Salalah Free Zone powered by 50 MW Dhofar Wind Farm.',
    freeZoneSynergyAr: 'المحطة النموذجية الكبرى بحرة صلالة للتنقل النظيف بالاستفادة من طاقة رياح ظفار (50 م.و).',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.salalah,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 1010
  },
  {
    id: 'oomco_dhofar_salalah_waterfront',
    nameEn: 'OOMCO EV - Salalah Coastal Waterfront Terminal',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة صلالة الساحلية الكبرى (شاطئ الدهاريز)',
    governorateEn: 'Dhofar',
    governorateAr: 'ظفار',
    zoneId: 'salalah',
    zoneNameEn: 'Salalah City Terminal',
    zoneNameAr: 'مدينة صلالة',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sultan Qaboos Street / Ad Dahariz Coastal Boulevard, Salalah, Dhofar',
    realAddressAr: 'شارع السلطان قابوس / شارع شاطئ الدهاريز الساحلي، صلالة، محافظة ظفار',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 5,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 17.0180,
    lng: 54.0920,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'The southern terminus of the 1,020 km national highway corridor in the heart of Salalah.',
    freeZoneSynergyAr: 'نقطة الوصول الجنوبية الكبرى لمسار الـ 1,020 كم السريع في قلب مدينة صلالة الساحلية.',
    realtimeOccupancyPct: 17,
    energyZoneLink: ENERGY_ZONES_DATABASE.salalah,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 1020
  },
  {
    id: 'oomco_dhofar_salalah_port_hub',
    nameEn: 'OOMCO EV - Salalah Deep-Water Port Eco-Depot',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ميناء صلالة للملاحة الدولية',
    governorateEn: 'Dhofar',
    governorateAr: 'ظفار',
    zoneId: 'salalah',
    zoneNameEn: 'Port of Salalah',
    zoneNameAr: 'ميناء صلالة',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Port of Salalah Deep-Water Container Terminal Highway, Raysut, Salalah',
    realAddressAr: 'طريق محطة الحاويات وميناء صلالة للملاحة العالمية، ريسوت، صلالة',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 16.9550,
    lng: 54.0150,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Dedicated commercial electric hub serving international maritime logistics and customs shuttles.',
    freeZoneSynergyAr: 'شواحن أساطيل الميناء لخدمة حاويات الشحن الدولي وسيارات التوزيع السريع بميناء صلالة.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.salalah,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 1015
  },
  {
    id: 'oomco_dhofar_mirbat_waypoint',
    nameEn: 'OOMCO EV - Mirbat Coastal Waypoint Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مرباط الساحلية السياحية',
    governorateEn: 'Dhofar',
    governorateAr: 'ظفار',
    zoneId: 'salalah',
    zoneNameEn: 'Mirbat Coastal Highway',
    zoneNameAr: 'ساحل مرباط',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Dhofar Coastal Highway (Route 49), Mirbat Heritage & Tourism Junction',
    realAddressAr: 'طريق ظفار الساحلي (طريق 49)، تقاطع ولاية مرباط السياحية، محافظة ظفار',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 16.9950,
    lng: 54.6950,
    status: 'PLANNED_2027_PIPELINE',
    yearCommissioned: 2027,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Eastern Dhofar coastal tourist and fishing fleet fast charger connecting Salalah to Hasik.',
    freeZoneSynergyAr: 'توسعة الشحن السريع شرق ظفار لخدمة حركة السياحة والصيد بين صلالة ومرباط وحاسك.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.salalah,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 1085
  },

  // ----------------------------------------------------
  // SOUTH & NORTH AL SHARQIYAH GOVERNORATES
  // ----------------------------------------------------
  {
    id: 'oomco_sharqiyah_bidbid_sur_rest',
    nameEn: 'OOMCO EV - Bidbid-Sur Expressway Rest Stop',
    nameAr: 'نفط عُمان (OOMCO EV) - استراحة طريق بدبد-صور السريع',
    governorateEn: 'North Al Sharqiyah',
    governorateAr: 'شمال الشرقية',
    zoneId: 'sur',
    zoneNameEn: 'Sharqiyah Expressway',
    zoneNameAr: 'طريق الشرقية السريع',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sharqiyah Expressway, Dima W’attayeen Integrated Rest Area & EV Hub',
    realAddressAr: 'طريق الشرقية السريع، استراحة دماء والطائيين المتكاملة ومحطة الشحن السريع',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.0150,
    lng: 58.3850,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Expressway charging oasis linking Muscat to the Eastern sands and historic fort towns.',
    freeZoneSynergyAr: 'واحة شحن سريعة على طريق الشرقية السريع تربط مسقط بالرمال والواحات التاريخية.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.sur,
    corridorTag: 'Sharqiyah',
    waypointKm: 75
  },
  {
    id: 'oomco_sharqiyah_ibra_commercial',
    nameEn: 'OOMCO EV - Ibra Commercial Regional Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة إبراء التجارية الإقليمية',
    governorateEn: 'North Al Sharqiyah',
    governorateAr: 'شمال الشرقية',
    zoneId: 'sur',
    zoneNameEn: 'Ibra University City',
    zoneNameAr: 'مدينة إبراء الجامعية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 23, Ibra Commercial Gateway & Regional Hospital Interchange',
    realAddressAr: 'طريق 23، المدخل التجاري لولاية إبراء وتقاطع المستشفى المرجعي',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.6950,
    lng: 58.5350,
    status: 'OPERATIONAL',
    yearCommissioned: 2023,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Central hub in Ibra servicing commercial intercity transit and university fleet.',
    freeZoneSynergyAr: 'المحطة المركزية بإبراء لخدمة النقل الجامعي والتجاري بقلب محافظة شمال الشرقية.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.sur,
    corridorTag: 'Sharqiyah',
    waypointKm: 140
  },
  {
    id: 'oomco_sharqiyah_kamil_wafi',
    nameEn: 'OOMCO EV - Al Kamil & Al Wafi Oasis Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة الكامل والوافي السريعة',
    governorateEn: 'South Al Sharqiyah',
    governorateAr: 'جنوب الشرقية',
    zoneId: 'sur',
    zoneNameEn: 'Al Kamil & Al Wafi',
    zoneNameAr: 'الكامل والوافي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 23 / Route 35 Junction, Al Kamil & Al Wafi Oasis Highway Plaza',
    realAddressAr: 'تقاطع طريق 23 مع طريق 35، محطة واحة الكامل والوافي السريعة',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.2150,
    lng: 59.2050,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Crucial junction connecting the expressway to coastal tourist routes and Jalan districts.',
    freeZoneSynergyAr: 'تقاطع استراتيجي يربط طريق الشرقية السريع بمسارات جعلان والساحل الشرقي.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.sur,
    corridorTag: 'Sharqiyah',
    waypointKm: 185
  },
  {
    id: 'oomco_sharqiyah_sur_industrial',
    nameEn: 'OOMCO EV - Sur Industrial City & Coastal Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مدينة صور الصناعية والساحلية',
    governorateEn: 'South Al Sharqiyah',
    governorateAr: 'جنوب الشرقية',
    zoneId: 'sur',
    zoneNameEn: 'Sur Industrial City',
    zoneNameAr: 'مدينة صور الصناعية',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Madayn Sur Industrial City Main Entrance Boulevard, Sur',
    realAddressAr: 'شارع المدخل الرئيسي لمدينة صور الصناعية (مدائن)، ولاية صور',
    powerKw: 160,
    portsCount: 6,
    availablePortsNow: 4,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.5720,
    lng: 59.5150,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Primary industrial and maritime transport charging station adjacent to Oman LNG and OMIFCO facilities in Sur.',
    freeZoneSynergyAr: 'محطة أساطيل صناعية كبرى ملاصقة لمجمعات الغاز المسال والسماد العماني بمدينة صور الصناعية.',
    realtimeOccupancyPct: 33,
    energyZoneLink: ENERGY_ZONES_DATABASE.sur,
    corridorTag: 'Sharqiyah',
    waypointKm: 230
  },
  {
    id: 'oomco_sharqiyah_sur_port_pipeline',
    nameEn: 'OOMCO EV - Sur Port Clean Logistics Terminal',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ميناء صور للوجستيات النظيفة',
    governorateEn: 'South Al Sharqiyah',
    governorateAr: 'جنوب الشرقية',
    zoneId: 'sur',
    zoneNameEn: 'Port of Sur',
    zoneNameAr: 'ميناء صور',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Sur Coastal Maritime Highway (Near Oman LNG & OMIFCO Facilities), Sur',
    realAddressAr: 'طريق صور الساحلي البحري (بجوار مجمع الشركة العمانية للغاز الطبيعي المسال)',
    powerKw: 180,
    portsCount: 6,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 22.5850,
    lng: 59.5350,
    status: 'PLANNED_2027_PIPELINE',
    yearCommissioned: 2027,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Maritime logistics depot servicing heavy coastal trucks and harbor commercial traffic.',
    freeZoneSynergyAr: 'محطة خدمات شحن بحري وتجاري لخدمة الشاحنات الثقيلة بميناء صور.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.sur,
    corridorTag: 'Sharqiyah',
    waypointKm: 235
  },

  // ----------------------------------------------------
  // AL DHAHIRAH GOVERNORATE
  // ----------------------------------------------------
  {
    id: 'oomco_dhahirah_ibri_gateway',
    nameEn: 'OOMCO EV - Ibri Oasis Desert Gateway Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة عبري واحة الظاهرة بوابة الربع الخالي',
    governorateEn: 'Al Dhahirah',
    governorateAr: 'الظاهرة',
    zoneId: 'highway',
    zoneNameEn: 'Ibri Regional Hub',
    zoneNameAr: 'محور عبري الإقليمي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 21, Ibri City Center & Empty Quarter Highway Junction, Al Dhahirah',
    realAddressAr: 'طريق 21، مركز ولاية عبري ومفترق طريق الربع الخالي، محافظة الظاهرة',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 3,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.2350,
    lng: 56.5120,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Located at the heart of Al Dhahirah near Ibri II 500MW Solar PV project, feeding transit between Oman and Saudi border.',
    freeZoneSynergyAr: 'محطة استراتيجية بعبري قرب محطة عبري 2 للطاقة الشمسية لدعم حركة السفر عبر منفذ الربع الخالي السعودي.',
    realtimeOccupancyPct: 25,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Dhahirah-Buraimi',
    waypointKm: 210
  },
  {
    id: 'oomco_dhahirah_yanqul_waypoint',
    nameEn: 'OOMCO EV - Yanqul Waypoint Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ينقل السريعة',
    governorateEn: 'Al Dhahirah',
    governorateAr: 'الظاهرة',
    zoneId: 'highway',
    zoneNameEn: 'Yanqul Mining Highway',
    zoneNameAr: 'طريق ينقل للتعدين',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 8, Yanqul Commercial Axis & Highway Stop, Al Dhahirah',
    realAddressAr: 'طريق 8، المحور التجاري لولاية ينقل، محافظة الظاهرة',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 23.5950,
    lng: 56.5450,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Serving agricultural and mineral freight traversing Al Dhahirah toward Sohar port.',
    freeZoneSynergyAr: 'خدمة شاحنات التعدين والزراعة المتجهة من الظاهرة إلى ميناء صحار.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.highway,
    corridorTag: 'Dhahirah-Buraimi',
    waypointKm: 260
  },

  // ----------------------------------------------------
  // AL BURAIMI GOVERNORATE
  // ----------------------------------------------------
  {
    id: 'oomco_buraimi_border_city',
    nameEn: 'OOMCO EV - Al Buraimi Border City Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة مدينة البريمي الحدودية',
    governorateEn: 'Al Buraimi',
    governorateAr: 'البريمي',
    zoneId: 'sohar',
    zoneNameEn: 'Al Buraimi Gateway',
    zoneNameAr: 'بوابة البريمي',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Route 7 (Sultan Qaboos Street), Al Buraimi Border City & Trade Corridor',
    realAddressAr: 'طريق 7 (شارع السلطان قابوس)، مدينة البريمي الحدودية، محافظة البريمي',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 2,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 24.2550,
    lng: 55.7650,
    status: 'OPERATIONAL',
    yearCommissioned: 2024,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Strategic cross-border fast-charging station servicing traffic between Al Ain (UAE) and Oman.',
    freeZoneSynergyAr: 'محطة حدودية سريعة لخدمة حركة التنقل اليومية بين مدينة العين والبريمي وسلطنة عُمان.',
    realtimeOccupancyPct: 50,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Dhahirah-Buraimi',
    waypointKm: 320
  },

  // ----------------------------------------------------
  // MUSANDAM GOVERNORATE
  // ----------------------------------------------------
  {
    id: 'oomco_musandam_khasab_harbor',
    nameEn: 'OOMCO EV - Khasab Coastal Harbor Station',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة ميناء خصب الساحلية بمحافظة مسندم',
    governorateEn: 'Musandam',
    governorateAr: 'مسندم',
    zoneId: 'sohar',
    zoneNameEn: 'Musandam Peninsula',
    zoneNameAr: 'شبه جزيرة مسندم',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Khasab Coastal Harbor Road (Port of Khasab), Musandam Governorate',
    realAddressAr: 'طريق ميناء خصب الساحلي، ولاية خصب، محافظة مسندم',
    powerKw: 120,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'Type 2'],
    lat: 26.1950,
    lng: 56.2450,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: false,
    freeZoneSynergyEn: 'Coastal fjord charging station connecting maritime ferries and tourist transport in Musandam.',
    freeZoneSynergyAr: 'أول محطة شحن سريعة بمحافظة مسندم لخدمة عبّارات الميناء والحركة السياحية بمضيق هرمز.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.sohar,
    corridorTag: 'Musandam',
    waypointKm: 420
  },

  // ----------------------------------------------------
  // AL MAZUNAH FREE ZONE (Southwestern Frontier)
  // ----------------------------------------------------
  {
    id: 'oomco_mazunah_cross_border',
    nameEn: 'OOMCO EV - Al Mazunah Freezone Cross-Border Hub',
    nameAr: 'نفط عُمان (OOMCO EV) - محطة المنطقة الحرة بالمزيونة عبر الحدود',
    governorateEn: 'Dhofar / Al Mazunah Border',
    governorateAr: 'ظفار / حدود المزيونة',
    zoneId: 'mazunah',
    zoneNameEn: 'Al Mazunah Free Zone',
    zoneNameAr: 'المنطقة الحرة بالمزيونة',
    operatorId: 'oomco_ev',
    operatorNameEn: 'Oman Oil Marketing Company (OOMCO)',
    operatorNameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)',
    hasElectricalCharge: true,
    isCarServiceStation: true,
    realAddressEn: 'Al Mazunah Free Zone Commercial Border Gate Plaza, Southwestern Dhofar',
    realAddressAr: 'المنطقة الحرة بالمزيونة، بوابة التبادل التجاري الحدودي، جنوب غرب ظفار',
    powerKw: 150,
    portsCount: 4,
    availablePortsNow: 0,
    connectorTypes: ['CCS2', 'CHAdeMO'],
    lat: 17.8420,
    lng: 52.8250,
    status: 'UNDER_CONSTRUCTION_2025_2026',
    yearCommissioned: 2025,
    tariffOmrPerKwh: 0.088,
    tariffTier: 'TIER_2',
    isFreeZoneHub: true,
    freeZoneSynergyEn: 'Frontier cross-border charging hub powering international commercial transport across the southwestern border.',
    freeZoneSynergyAr: 'محطة حدودية استراتيجية لشحن الشاحنات ومركبات التجارة العابرة عبر المنطقة الحرة بالمزيونة.',
    realtimeOccupancyPct: 0,
    energyZoneLink: ENERGY_ZONES_DATABASE.mazunah,
    corridorTag: 'Adam-Thumrait-Salalah',
    waypointKm: 1180
  }
];

// Operator brand constant (exclusively Oman Oil Company)
export const EV_STATION_OPERATORS = [
  { 
    id: 'oomco_ev', 
    nameEn: 'Oman Oil Marketing Company (OOMCO EV)', 
    nameAr: 'شركة النفط العمانية للتسويق (نفط عُمان)', 
    color: '#10b981', 
    icon: 'fa-bolt-lightning' 
  }
];
