const fs = require('fs');

function translateFile(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');
  let original = content;

  // In Dashboard.tsx we have English strings
  const dict = {
    "Official Investment-Grade Report": "التقرير الرسمي للجدوى الاستثمارية",
    "Project:": "المشروع:",
    "Technical Engineering AI": "الذكاء الاصطناعي للهندسة التقنية",
    "Installed Capacity": "القدرة المثبتة",
    "Energy Output": "إنتاج الطاقة",
    "Benchmark CAPEX": "النفقات الرأسمالية المعيارية",
    "TRL Level": "مستوى الجاهزية التكنولوجية",
    "Financial Modeling AI": "الذكاء الاصطناعي للنمذجة المالية",
    "Realistic CAPEX": "النفقات الرأسمالية الواقعية",
    "Annual OPEX": "النفقات التشغيلية السنوية",
    "Payback Period": "فترة الاسترداد",
    "IRR (Est.)": "معدل العائد الداخلي (تقديري)",
    "LCOE / Unit Cost": "التكلفة المستوية للطاقة / تكلفة الوحدة",
    "Investment Auditor": "مدقق الاستثمار",
    "Audit Classification": "تصنيف التدقيق",
    "Recalculated Cost": "التكلفة المعاد حسابها",
    "Funding Gap": "فجوة التمويل",
    "Stress Test Results": "نتائج اختبار تحمل الضغط",
    "Revenue -10%": "الإيرادات -10%",
    "OPEX +15%": "نفقات التشغيل +15%",
    "Production -10%": "الإنتاج -10%",
    "Risk Assessment AI": "الذكاء الاصطناعي لتقييم المخاطر",
    "Capital Adequacy": "كفاية رأس المال",
    "Risk Level": "مستوى الخطر",
    "Market Volatility": "تقلبات السوق",
    "Regulatory Risk": "المخاطر التنظيمية",
    "Feedstock Stability": "استقرار المواد الخام",
    "Report Generated By": "أُنشئ التقرير بواسطة",
    "BioFuel Insight AI Engine v2.5": "محرك الذكاء الاصطناعي BioFuel Insight v2.5",
    "Print Report": "طباعة التقرير",
    "Project Analysis": "تحليل المشروع",
    "Risk Exposure": "التعرض للمخاطر",
    "Official Report": "التقرير الرسمي",
    "Export CSV": "تصدير CSV",
    "Feasibility Score": "درجة الجدوى",
    "Investment Verdict": "قرار الاستثمار",
    "Rating:": "التقييم:",
    "Corporate Tax (Oman)": "ضريبة الشركات (عُمان)",
    "Applied": "مُطبقة",
    "Net Profit After Tax included in IRR": "يشمل معدل العائد الداخلي صافي الربح بعد الضريبة",
    "Dynamic AI Scoring": "التسجيل الديناميكي للذكاء الاصطناعي",
    "SWOT Intelligence Analyze": "تحليل ذكاء SWOT",
    "Strengths": "نقاط القوة",
    "Opportunities": "الفرص",
    "Weaknesses": "نقاط الضعف",
    "Threats": "التهديدات",
    "Omani Localization Logic": "منطق التوطين العماني",
    "Industry Tax (Oman)": "ضريبة الصناعة (عُمان)",
    "Omanization Cost Allocation": "تخصيص تكلفة التعمين",
    "35% Minimum Quota Applied": "الحد الأدنى مطبق بنسبة 35%",
    "In USD": "بالدولار الأمريكي",
    "Industrial Utility Tariffs": "تعرفة المرافق الصناعية",
    "Legal & Permit Roadmap": "خارطة الطريق القانونية والتصاريح",
    "Primary Authority:": "الجهة الأساسية:",
    "Executive Summary (AI Generated)": "الملخص التنفيذي (من إنشاء الذكاء الاصطناعي)",
    "Aligned with Oman Vision 2040 Economic Diversification": "متوافق مع التنويع الاقتصادي لرؤية عُمان 2040",
    "Monte Carlo Summary": "ملخص مونت كارلو",
    "Stress Test: 10% Market Price Drop": "اختبار الضغط: انخفاض سعر السوق بنسبة 10%",
    "New Payback": "استرداد جديد",
    "Viability": "الجدوى",
    "Financial Performance Metrics": "مقاييس الأداء المالي",
    "Industrial Benchmarks Applied": "تم تطبيق المعايير الصناعية",
    "Realistic Required CAPEX": "النفقات الرأسمالية المطلوبة الواقعية",
    "Investor Budget": "ميزانية المستثمر",
    "Installed Cost per": "التكلفة المثبتة لـ",
    "Annual Revenue": "الإيرادات السنوية",
    "Gross Profit": "إجمالي الربح",
    "Annual Production": "الإنتاج السنوي",
    "Sensitivity Stress Tests": "اختبارات تحمل الحساسية",
    "Price Drop (-10%)": "انخفاض السعر (-10%)",
    "OPEX Increase (+15%)": "زيادة نفقات التشغيل (+15%)",
    "Production Drop (-10%)": "انخفاض الإنتاج (-10%)",
    "Investment Sensitivity Visualizer": "متخيل حساسية الاستثمار",
    "Visualizing how market shifts impact your ROI": "تصور كيف تؤثر تحولات السوق على عائد الاستثمار الخاص بك",
    "Expert Counsel & Actionable Recommendations": "مشورة الخبراء وتوصيات قابلة للتنفيذ",
    "Strategic Advisory": "استشارات استراتيجية",
    "Capital Expenditure Profile": "ملف النفقات الرأسمالية",
    "Oman Vision 2040 Alignment": "التوافق مع رؤية عُمان 2040",
    "Energy Diversification": "تنوع الطاقة",
    "Industrial Development": "التنمية الصناعية",
    "Investor Perspective AI": "الذكاء الاصطناعي من منظور المستثمر",
    "Return Potential": "إمكانات العائد",
    "Capital Intensity": "كثافة رأس المال",
    "Scalability Rating": "تقييم قابلية التوسع",
    "Market Demand": "طلب السوق",
    "Critical Risk Matrix": "مصفوفة المخاطر الحرجة",
    "Local Consistency Review": "مراجعة الاتساق المحلي",
    "Consistency:": "الاتساق:",
    "Model Assumptions & Transparency": "افتراضات النموذج والشفافية",
    "Key Benchmarks": "المعايير الرئيسية",
    "Analysis Limitations": "قيود التحليل"
  };

  // Convert these strings into t('English', 'Arabic')
  for (const [en, ar] of Object.entries(dict)) {
    // Escape string for regex
    const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`>\\s*${escapeRegExp(en)}\\s*<`, 'g');
    content = content.replace(regex, `>{t("${en}", "${ar}")}<`);

    const regex2 = new RegExp(`>\\s*${escapeRegExp(en)}:\\s*<`, 'g');
    content = content.replace(regex2, `>{t("${en}:", "${ar}:")}<`);
  }

  // Handle specific dynamic interpolations if needed, but the simple replace works for >Text<

  if (original !== content) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log('Translated UI in', filePath);
  }
}

['Dashboard.tsx', 'ProposalGenerator.tsx', 'ResearchDashboard.tsx'].forEach(f => {
  if(fs.existsSync(f)) {
    translateFile(f);
  } else {
    // it's in src maybe?
  }
});
